# Generated by Django 2.2.24 on 2021-08-28 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elepioApp', '0002_auto_20210815_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='board',
            name='bg_color',
            field=models.CharField(default='#FFFFFF', max_length=30),
        ),
        migrations.AddField(
            model_name='board',
            name='height',
            field=models.IntegerField(default=''),
        ),
        migrations.AddField(
            model_name='board',
            name='player_count',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='board',
            name='player_max',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='board',
            name='width',
            field=models.IntegerField(default=''),
        ),
        migrations.AddField(
            model_name='player',
            name='color',
            field=models.IntegerField(default='#FFFFFF'),
        ),
        migrations.AddField(
            model_name='player',
            name='name',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='player',
            name='pos_x',
            field=models.CharField(max_length=100000, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='pos_y',
            field=models.CharField(max_length=100000, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='radius',
            field=models.CharField(default='10px', max_length=5),
        ),
        migrations.AddField(
            model_name='player',
            name='type',
            field=models.CharField(default='square', max_length=50),
        ),
    ]
