# Generated by Django 2.2.24 on 2021-09-12 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elepioApp', '0003_auto_20210828_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='radius',
            field=models.IntegerField(default=5),
        ),
    ]
