# Generated by Django 2.2.24 on 2021-09-12 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elepioApp', '0004_auto_20210911_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='bg_color',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
        migrations.AlterField(
            model_name='board',
            name='height',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='board',
            name='width',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='player',
            name='color',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
        migrations.AlterField(
            model_name='player',
            name='pos_x',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='pos_y',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='type',
            field=models.CharField(default='circle', max_length=50),
        ),
    ]
