# Generated by Django 2.2.24 on 2021-09-12 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elepioApp', '0006_auto_20210911_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='pos_x',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='pos_y',
            field=models.IntegerField(null=True),
        ),
    ]
