# Generated by Django 2.2.24 on 2021-09-25 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elepioApp', '0007_auto_20210911_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='board',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='elepioApp.Board'),
        ),
    ]
